---
title: "Practical assignment discounting"
author: "X. Pouwels"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aim
This assignment aims to introduce you to the concept of discounting in health economic evaluations, using a fictive example containing 3 interventions.    

# Required packages

1. `rstudioapi`: for loading the data in case the working directory is not at the same location as the source file `Assignment_start_discounting.R` for performing the assignment  
2. `tidyverse`: suite of packages for data manipulation and plotting your results  

# Instuctions
  
1. Download the `Assignment_start_discounting.R` and `data_discount.rds` files from the Canvas page and save them **in the same folder**.  
2. Open the `Assignment_start_discounting.R` file. In this file, the instructions from below are copied and objects names are already define for you to perform the assignment and to structure your code.     
3. Load the data for this assignment (`data_discount.rds`) using the readRDS() function, and assign it to an object called `df_thx`.     
4. When performing the assignment, please document your code (using R markdown for instance)  
5. Please keep your answers for the discussion  

# `df_thx` object
This object contains 7 variables:  

- Year = the year in which incremental costs and effects have been incurred (from Year 0 to 12) 
- Inc_cost_A = incremental costs of intervention A (in the different years)  
- Inc_QALY_A = incremental effects (QALYs) of intervention A (in the different years)  
- Inc_cost_B = incremental costs of intervention B (in the different years)  
- Inc_QALY_B = incremental effects (QALYs) of intervention B (in the different years)  
- Inc_cost_C = incremental costs of intervention C (in the different years)  
- Inc_QALY_C = incremental effects (QALYs) of intervention C (in the different years)  
**Assume that all incremental costs and QALYs of these interventions are calculated against usual care.**

\newpage
# Assignment and questions  

1. Define a new object `r_disc`, which is the discount rate that will be used in the current assignment, and set its value to `0.05` (meaning 5% discount annually)
2. Calculate the total undiscounted incremental costs and effects for each intervention  
3. Calculate the **undiscounted** ICERs for each of these interventions using the total incremental costs and effects you calculated under step 2  
3.a. Question: what are the total incremental costs and effects for each intervention? Which intervention provides the highest **undiscounted** incremental costs and effects?  
3.b. Question: what are the ICERs for each intervention? Which intervention provides the best value for money (most favourable ICER) based on these **undiscounted** incremental costs and effects?  
4. Create a vector of discount weights for Years 0 to 12, using `r_disc`, the `Year` column of the `df_thx` data frame, and the formula: $$w_i = \frac{1} {(1+r)^{t_i}}$$ where $w_i$ is the discount weight in year $i$, $r$ the discount rate, and $t_i$ year $i$.  
5. Apply discounting on the incremental effects and costs (by multiplying each column by the vector of discount weights for instance) to convert these to their present value. Report the discounted effects and costs in new columns of `df_thx` called `Inc_cost_A_d`, `Inc_QALY_A_d`, `Inc_cost_B_d`, `Inc_QALY_B_d`, `Inc_cost_C_d`, `Inc_QALY_C_d`.   
6. Calculate the total **discounted** incremental costs and effects, and ICERs for each intervention.  
6.a. Question: what are the total **discounted** incremental costs and effects for each intervention? Which intervention provides the highest **discounted** incremental costs and effects?  
6.b. Question: what are the **discounted** ICERs for each intervention? Which intervention provides the best value for money (most favourable ICER) based on these **discounted** incremental costs and effects?  
6.c. Can you explain the difference between the results obtained under step 6 and steps 2 and 3?  
7. Now apply a discount rate of **10%**  and calculate the **discounted** incremental costs and effects, and ICERs for each intervention again. Which intervention provides the most and least value for money? Can you explain these results? Are these comparable with results obtained in step 6?  
8. Can you explain why, even with a small discount rate (for example 0.1%) cost-effectiveness with discounting is always worse than cost-effectiveness without discounting?